[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/profil"
  to = "/profil.html"
  status = 200

[[redirects]]
  from = "/connexion"
  to = "/connexion.html"
  status = 200

[[redirects]]
  from = "/inscription"
  to = "/inscription.html"
  status = 200

[[redirects]]
  from = "/soins-energetiques"
  to = "/services-energetiques.html"
  status = 200

[[redirects]]
  from = "/accompagnement"
  to = "/accompagnement.html"
  status = 200

[[redirects]]
  from = "/soins-direct"
  to = "/soins-direct.html"
  status = 200

[[redirects]]
  from = "/histoire"
  to = "/histoire.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
